CREATE TABLE USER(
    idx BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT ,
    user_name VARCHAR(255) NOT NULL ,
    email VARCHAR(255) NOT NULL
);
CREATE TABLE USER_LANGUAGE(
    idx BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT ,
    user_idx BIGINT NOT NULL,
    use_language VARCHAR(50) NOT NULL,
    amount BIGINT NOT NULL,
    FOREIGN KEY (user_idx) REFERENCES USER(idx) ON DELETE CASCADE
);
CREATE TABLE USER_LANGUAGE_EXP(
    user_idx BIGINT NOT NULL,
    language_idx BIGINT NOT NULL,
    FOREIGN KEY (user_idx) REFERENCES USER (idx) ,
    FOREIGN KEY (language_idx) REFERENCES USER_LANGUAGE(idx) ON UPDATE CASCADE ON DELETE CASCADE,
    exp BIGINT NOT NULL
);

ALTER TABLE USER ADD CONSTRAINT USER_IDX UNIQUE (email);
ALTER TABLE USER_LANGUAGE ADD CONSTRAINT USER_LANGUAGE_IDX UNIQUE (user_idx, use_language);
ALTER TABLE USER_LANGUAGE_EXP ADD CONSTRAINT USER_EXP_UQ UNIQUE (user_idx, language_idx);